// The blue-noise tile is BINARY, and the published package ships `dist/` only —
// so `assets/blue-noise.rgba` is unreachable from `@vibecook/ice/ground/packs`,
// where the mat pack needs it (design-013 §8 B8, D-B8.1). This writes it into a
// TypeScript module the bundler can follow, exactly as `wgsl-to-ts.mjs` does for
// the shader text and for the same reason (D-B1.3's precedent). @ice/desk's copy
// since design-015 D1 — packages/ground's tool but for the package name (the two
// packages never import each other, D-D0.3).
//
// base64, not a number array: 65,536 bytes as decimal literals is ~250 KB of
// source and a parse cost on every import; base64 is ~87 KB and decodes once,
// lazily, on the first `blueNoise()` call.
//
//   node tools/noise-to-ts.mjs          → src/assets/blue-noise.gen.ts
//   node tools/noise-to-ts.mjs --check  → exit 1 if the module is stale (the gate)
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const source = resolve(root, "assets/blue-noise.rgba");
const target = resolve(root, "src/assets/blue-noise.gen.ts");

const bytes = readFileSync(source);
// 128 × 128 × rgba8. Asserted here rather than in the module: a wrong-sized tile
// is a build-time mistake, and the pass would upload it as a silently wrong texture.
const SIDE = 128;
if (bytes.length !== SIDE * SIDE * 4) {
  console.error(`blue-noise.rgba is ${bytes.length} bytes; expected ${SIDE * SIDE * 4} (${SIDE}² rgba8)`);
  process.exit(1);
}

const b64 = bytes.toString("base64");
const chunks = [];
for (let i = 0; i < b64.length; i += 120) chunks.push(`  "${b64.slice(i, i + 120)}"`);

const out = `// GENERATED by tools/noise-to-ts.mjs from assets/blue-noise.rgba — do not edit.
// \`pnpm --filter @ice/desk gen:noise\` regenerates it; \`gen:check\` fails the gate when it is stale.
// The .rgba file is the source; this module is how it reaches a published bundle
// (the package ships \`dist/\` only, and the mat pack needs the tile at runtime).

/** The tile is square and rgba8: ${SIDE} × ${SIDE} × 4 = ${bytes.length} bytes. */
export const BLUE_NOISE_SIZE = ${SIDE};

const B64 =
${chunks.join(" +\n")};

let decoded: Uint8Array<ArrayBuffer> | null = null;

/**
 * The 128×128 rgba8 blue-noise tile the cutting mat samples, decoded once.
 *
 * Hand it to the pack's injection point — \`matPass.setNoise(blueNoise())\` — the
 * same seam a lab feeds from a \`?url\` fetch. Decoding is lazy so a board that
 * never registers the mat pays nothing for it.
 */
export function blueNoise(): Uint8Array<ArrayBuffer> {
  if (decoded !== null) return decoded;
  const bin = atob(B64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  decoded = out;
  return out;
}
`;

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(target, "utf8");
  } catch {
    // absent counts as stale
  }
  if (current !== out) {
    console.error("src/assets/blue-noise.gen.ts is stale — run `pnpm --filter @ice/desk gen:noise`");
    process.exit(1);
  }
  console.log("blue-noise.gen.ts is fresh");
} else {
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, out);
  console.log(`wrote ${relative(root, target)} (${bytes.length} bytes → ${b64.length} base64 chars)`);
}
