// The WGSL is the source; this writes it into a TypeScript module so the compose
// entry ships its shaders with no bundler loader (design-013 B1, D-B1.3; @ice/desk at design-015 D1). Byte
// for byte: the oracle reads the .wgsl files from disk and composes the same text.
//   node tools/wgsl-to-ts.mjs          → src/shaders.gen.ts
//   node tools/wgsl-to-ts.mjs --check  → exit 1 if the module is stale (the gate)
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";
const root = resolve(import.meta.dirname, "..");
const dir = resolve(root, "shaders");
const files = [];
const walk = (d) => { for (const n of readdirSync(d).sort()) { const p = join(d, n); if (statSync(p).isDirectory()) walk(p); else if (n.endsWith(".wgsl")) files.push(p); } };
walk(dir);
const entries = files.map((p) => `  ${JSON.stringify(relative(dir, p))}: ${JSON.stringify(readFileSync(p, "utf8"))},`).join("\n");
const out = `// GENERATED by tools/wgsl-to-ts.mjs from shaders/**/*.wgsl — do not edit.\n// \`pnpm --filter @ice/desk gen:shaders\` regenerates it; \`gen:check\` fails the gate when it is stale.\n// The .wgsl files are the source: the Node oracle reads them from disk and composes byte-identical text.\nexport const WGSL = {\n${entries}\n} as const;\nexport type WgslFile = keyof typeof WGSL;\n`;
const target = resolve(root, "src/shaders.gen.ts");
if (process.argv.includes("--check")) {
  let current = ""; try { current = readFileSync(target, "utf8"); } catch {}
  if (current !== out) { console.error("src/shaders.gen.ts is stale — run `pnpm --filter @ice/desk gen:shaders`"); process.exit(1); }
  console.log("shaders.gen.ts is fresh");
} else { writeFileSync(target, out); console.log(`wrote ${relative(root, target)} (${files.length} files)`); }
