// What the desk is FED (the render map's finding #2: the product never fed the mat before): the app's GENERATED gobo
// plates for the product desk (gobo-palm-1 into slot `c`, gobo-canopy-1 into `b` — never the study's), fetched once and
// kept. The oracle's own fixtures — its plates, its glyph atlas, the note's ink raster — are the rigs' (src/rig/,
// design-015 D7, D-D7-C.3).

import canopyUrl from "../assets/gobo-canopy-1.rgba?url";
import palmUrl from "../assets/gobo-palm-1.rgba?url";

export async function bytesOf(url: string): Promise<Uint8Array<ArrayBuffer>> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url}: ${res.status}`);
  return new Uint8Array(await res.arrayBuffer());
}

/** The product's plates — generated by tools/make-gobo-plate.mjs (`palm --seed 1`, `canopy --seed 1`); `gen:check` holds the committed bytes to it (D7). */
export interface ProductPlates { readonly c: Uint8Array<ArrayBuffer>; readonly b: Uint8Array<ArrayBuffer> }
let plates: Promise<ProductPlates> | null = null;
export const productPlates = (): Promise<ProductPlates> => {
  plates ??= Promise.all([bytesOf(palmUrl), bytesOf(canopyUrl)]).then(([c, b]) => ({ c, b }));
  return plates;
};
